enum STATUS_CODE_ENUM {
    SUCCESS = 200,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    INTERNAL_SERVER_ERROR = 500,
    SERVICE_UNAVAILABLE = 503,
}

enum USER_STATUS_ENUM {
    ACTIVE = "ACTIVE",
    BLOCKED = "BLOCKED"
}

enum MENU_STATUS_ENUM {
    VISIBLE = "VISIBLE",
    INVISIBLE = "INVISIBLE"
}

enum PACKAGE_STATUS_ENUM {
    VISIBLE = "VISIBLE",
    INVISIBLE = "INVISIBLE"
}

enum SOCIAL_TASK_STATUS_ENUM {
    VISIBLE = "VISIBLE",
    INVISIBLE = "INVISIBLE"
}

enum SOCIAL_TASK_TYPE_ENUM {
    FOLLOW_X = "FOLLOW_X",
    LIKE_X_POST = "LIKE_X_POST",
    RETWEET_X_POST = "RETWEET_X_POST",
    COMMENT_X_POST = "COMMENT_X_POST",
    JOIN_TELEGRAM_CHANNEL = "JOIN_TELEGRAM_CHANNEL",
    SUBSCRIBE_YOUTUBE_CHANNEL = "SUBSCRIBE_YOUTUBE_CHANNEL",
    WATCH_YOUTUBE_VIDEO = "WATCH_YOUTUBE_VIDEO",
    JOIN_DISCORD_GROUP = "JOIN_DISCORD_GROUP",
    JOIN_DISCORD_CHANNEL = "JOIN_DISCORD_CHANNEL",
    CONNECT_WALLET = "CONNECT_WALLET",
    HODL_TOKEN = "HODL_TOKEN",
    RECEIVE_TOKEN = "RECEIVE_TOKEN",
    INVITE_FRIEND = "INVITE_FRIEND",
    REPORT_BUGS = "REPORT_BUGS"
}

enum SOCIAL_TASK_GROUP_ENUM {
    X = "X",
    TELEGRAM = "TELEGRAM",
    YOUTUBE = "YOUTUBE",
    DISCORD = "DISCORD",
    WEB3 = "WEB3",
    OTHER = "OTHER",
}

const SOCIAL_TASK_TYPE = [
    { type: SOCIAL_TASK_TYPE_ENUM.FOLLOW_X, group: SOCIAL_TASK_GROUP_ENUM.X },
    { type: SOCIAL_TASK_TYPE_ENUM.LIKE_X_POST, group: SOCIAL_TASK_GROUP_ENUM.X },
    { type: SOCIAL_TASK_TYPE_ENUM.RETWEET_X_POST, group: SOCIAL_TASK_GROUP_ENUM.X },
    { type: SOCIAL_TASK_TYPE_ENUM.COMMENT_X_POST, group: SOCIAL_TASK_GROUP_ENUM.X },
    { type: SOCIAL_TASK_TYPE_ENUM.JOIN_TELEGRAM_CHANNEL, group: SOCIAL_TASK_GROUP_ENUM.TELEGRAM },
    { type: SOCIAL_TASK_TYPE_ENUM.SUBSCRIBE_YOUTUBE_CHANNEL, group: SOCIAL_TASK_GROUP_ENUM.YOUTUBE },
    { type: SOCIAL_TASK_TYPE_ENUM.WATCH_YOUTUBE_VIDEO, group: SOCIAL_TASK_GROUP_ENUM.YOUTUBE },
    { type: SOCIAL_TASK_TYPE_ENUM.JOIN_DISCORD_GROUP, group: SOCIAL_TASK_GROUP_ENUM.DISCORD },
    { type: SOCIAL_TASK_TYPE_ENUM.JOIN_DISCORD_CHANNEL, group: SOCIAL_TASK_GROUP_ENUM.DISCORD },
    { type: SOCIAL_TASK_TYPE_ENUM.CONNECT_WALLET, group: SOCIAL_TASK_GROUP_ENUM.WEB3 },
    { type: SOCIAL_TASK_TYPE_ENUM.HODL_TOKEN, group: SOCIAL_TASK_GROUP_ENUM.WEB3 },
    { type: SOCIAL_TASK_TYPE_ENUM.RECEIVE_TOKEN, group: SOCIAL_TASK_GROUP_ENUM.WEB3 },
    { type: SOCIAL_TASK_TYPE_ENUM.INVITE_FRIEND, group: SOCIAL_TASK_GROUP_ENUM.OTHER },
    { type: SOCIAL_TASK_TYPE_ENUM.REPORT_BUGS, group: SOCIAL_TASK_GROUP_ENUM.OTHER },
];

enum INVESTMENT_STATUS_ENUM {
    ACTIVE = "ACTIVE",
    CLOSED = "CLOSED",
    CANCELLED = "CANCELLED"
}

enum USER_TASK_STATUS_ENUM {
    READY_START = "READY_START",
    STARTED = "STARTED",
    CLAIMED = "CLAIMED" 
}

enum POINT_TYPE_ENUM {
    COMPLETE_TASK = "COMPLETE_TASK"
}

enum PROFIT_TYPE_ENUM {
    INVESTMENT = 'INVESTMENT',
    REFERRAL_INVESTMENT = 'REFERRAL_INVESTMENT',
    OTHER = 'OTHER',
}

enum PROFIT_STATUS_ENUM {
    OFFICIAL  = "OFFICIAL",
    TEMPORARY = "TEMPORARY"
}

enum USER_WITHDRAWAL_STATUS_ENUM {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}

export { 
    STATUS_CODE_ENUM, 
    USER_STATUS_ENUM, 
    MENU_STATUS_ENUM,
    PACKAGE_STATUS_ENUM,
    INVESTMENT_STATUS_ENUM,
    POINT_TYPE_ENUM,
    PROFIT_TYPE_ENUM,
    SOCIAL_TASK_STATUS_ENUM,
    SOCIAL_TASK_TYPE_ENUM,
    SOCIAL_TASK_GROUP_ENUM,
    USER_TASK_STATUS_ENUM,
    PROFIT_STATUS_ENUM,
    USER_WITHDRAWAL_STATUS_ENUM,
    SOCIAL_TASK_TYPE
};